name: Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Build
    - run: make
      working-directory: ../../src
  
