name: Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: windows-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Build library
      run: make dll
      working-directory: src/
    - name: Build examples
      run: make examples
      working-directory: src/
    - name: Cleanup
      run: make clean
      working-directory: src
